import { Carousel } from "@trendyol-js/react-carousel";
import React from "react";

export default function SwipeableCarousel() {
  return (
    <div className="container mt-2 px-0" style={{ borderRadius: "10px" }}>
      <Carousel
        show={window.innerWidth < 990 ? 3.5 : 9.5}
        slide={3}
        swiping={true}
        rightArrow={false}
        leftArrow={false}
        responsive={true}
      >
        <div>
          <img
            src="https://images-na.ssl-images-amazon.com/images/G/01/DiscoTec/2022/HOL22/GW/DesktopShoveler/Shoveler_CML_1x._CB608464074_.jpg"
            class="img-fluid"
            alt="..."
          />
        </div>
        <div>
          <img
            src="https://images-na.ssl-images-amazon.com/images/G/01/DiscoTec/2022/HOL22/GW/DesktopShoveler/Shoveler_StockingStuffers_1x._CB606658764_.jpg"
            class="img-fluid"
            alt="..."
          />
        </div>
        <div>
          <img
            src="https://images-na.ssl-images-amazon.com/images/G/01/DiscoTec/2022/HOL22/GW/DesktopShoveler/Shoveler_Fashion_1x._CB608464074_.jpg"
            class="img-fluid"
            alt="..."
          />
        </div>
        <div>
          <img
            src="https://images-na.ssl-images-amazon.com/images/G/01/DiscoTec/2022/HOL22/GW/DesktopShoveler/Shoveler_CML_1x._CB608464074_.jpg"
            class="img-fluid"
            alt="..."
          />
        </div>
        <div>
          <img
            src="https://images-na.ssl-images-amazon.com/images/G/01/DiscoTec/2022/HOL22/GW/DesktopShoveler/Shoveler_StockingStuffers_1x._CB606658764_.jpg"
            class="img-fluid"
            alt="..."
          />
        </div>
        <div>
          <img
            src="https://images-na.ssl-images-amazon.com/images/G/01/DiscoTec/2022/HOL22/GW/DesktopShoveler/Shoveler_Fashion_1x._CB608464074_.jpg"
            class="img-fluid"
            alt="..."
          />
        </div>
        <div>
          <img
            src="https://images-na.ssl-images-amazon.com/images/G/01/DiscoTec/2022/HOL22/GW/DesktopShoveler/Shoveler_CML_1x._CB608464074_.jpg"
            class="img-fluid"
            alt="..."
          />
        </div>
        <div>
          <img
            src="https://images-na.ssl-images-amazon.com/images/G/01/DiscoTec/2022/HOL22/GW/DesktopShoveler/Shoveler_StockingStuffers_1x._CB606658764_.jpg"
            class="img-fluid"
            alt="..."
          />
        </div>
        <div>
          <img
            src="https://images-na.ssl-images-amazon.com/images/G/01/DiscoTec/2022/HOL22/GW/DesktopShoveler/Shoveler_Fashion_1x._CB608464074_.jpg"
            class="img-fluid"
            alt="..."
          />
        </div>
        <div>
          <img
            src="https://images-na.ssl-images-amazon.com/images/G/01/DiscoTec/2022/HOL22/GW/DesktopShoveler/Shoveler_CML_1x._CB608464074_.jpg"
            class="img-fluid"
            alt="..."
          />
        </div>
        <div>
          <img
            src="https://images-na.ssl-images-amazon.com/images/G/01/DiscoTec/2022/HOL22/GW/DesktopShoveler/Shoveler_StockingStuffers_1x._CB606658764_.jpg"
            class="img-fluid"
            alt="..."
          />
        </div>
        <div>
          <img
            src="https://images-na.ssl-images-amazon.com/images/G/01/DiscoTec/2022/HOL22/GW/DesktopShoveler/Shoveler_Fashion_1x._CB608464074_.jpg"
            class="img-fluid"
            alt="..."
          />
        </div>
      </Carousel>
    </div>
  );
}
